// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "./config/env.js";
import { defineConfig } from "prisma/config";

const region = process.env.DATABASE_REGION
const hostname = process.env.DATABASE_HOSTNAME
const databaseName = process.env.DATABASE_NAME
const port = process.env.DATABASE_PORT
const username = process.env.DATABASE_USERNAME
const password = process.env.DATABASE_TEMP_TOKEN ?? process.env.DATABASE_PASSWORD;

const connectionString = `postgresql://${username}:${encodeURIComponent(password)}@${hostname}:${port}/${databaseName}?schema=public`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: connectionString,
  },
});
