services:
  api:
    build: .
    ports: 
      - 3000:3000
    env_file:
      - .env.local
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: change-me
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:
